version: "3.3"

services:

  node:
    restart: always
    build: ./node/
    expose:
      - "8080"
    networks:
      node-nginx:
        aliases:
          - express

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - django-media:/data/web/djangoAngular/media
      - django-static:/data/web/djangoAngular/static
    networks:
      node-nginx:
      django-nginx:
      default:
        aliases:
          - www.aprenderangular.com
    depends_on:
      - web
      - node

  web:
    restart: always
    build: ./web/
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    env_file: env
    volumes:
      - django-media:/data/web/djangoAngular/media
      - django-static:/data/web/djangoAngular/static
    command: /usr/bin/gunicorn djangoAngular.wsgi:application -w 2 -b :8000
    networks:
      django-nginx:
      django-postgres:

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
      - db:/var/lib/postgresql/data
    env_file: env
    expose:
      - "5432"
    networks:
      django-postgres:

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    networks:
      django-postgres:

  data:
    restart: always
    image: alpine
    volumes:
      - db:/var/lib/postgresql/data
    command: "true"

volumes:
  db:
  django-media:
  django-static:

networks:
  node-nginx:
  django-nginx:
  django-postgres: