# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180310_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='sdfsdf', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='sdfd', upload_to='images'),
            preserve_default=False,
        ),
    ]
