# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 00:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiveImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('caption', models.CharField(blank=True, default=None, max_length=100)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, height_field='height', upload_to='images/%Y/%m/%d/', width_field='width')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_author',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'body': []}),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.ResponsiveImage'),
        ),
    ]
