# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180421_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsiveimage',
            options={'ordering': ('-created',)},
        ),
    ]
