# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_responsiveimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiveimage',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field='height', upload_to='images/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
