# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180421_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsiveimage',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='responsiveimage',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
