# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180421_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsiveimage',
            name='desktop',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='responsiveimage',
            name='tablet',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
