# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_responsiveimage_portrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsiveimage',
            old_name='portrait',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='responsiveimage',
            old_name='thumbnail',
            new_name='phone_portrait',
        ),
        migrations.AddField(
            model_name='responsiveimage',
            name='tablet_portrait',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
